services:
  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_USER: defaultUser
      #%40 = @  
      MYSQL_PASSWORD: MySq%40root170520
      MYSQL_DATABASE: ecoride_project
      MYSQL_ROOT_PASSWORD: RoOt%40root170520
    volumes:
      - db-data:/var/lib/data
  app:
    image: php:8.2-apache
    ports: -8000 -80
    environment:
      DATABASE_URL: "mysql://defaultUser:MySq%40root170520@db:3306/ecoride?serverVersion=8.4&charset=utf8mb4"
      APP_ENV: dev
      MESSENGER_TRANSPORT_DSN: doctrine://default?auto_setup=0
    depends_on: [ db ]

  volumes:
    db-data:  
